# vim: syntax=ruby filetype=ruby
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'ldez/tap'
tap 'buildpack/tap'

cask 'vlc'
cask 'microsoft-office'
cask 'google-ads-editor'
cask 'firefox'
cask 'slack'
cask 'google-chrome'
cask 'forticlient'
cask 'the-unarchiver'
cask 'anydesk'
cask 'whatsapp'
cask 'screaming-frog-seo-spider'
cask 'termius'
cask 'spotify'